"use client";
import {useMemo,useState} from "react";
import {questions} from "@/data/backsplash";
import {evaluateBacksplash} from "@/lib/strategyEngine";
import type {DecisionAnswers,Experience,Goal,Ownership,Priority} from "@/types/decision";
import {ChoiceCard} from "./ChoiceCard";import {ClarityBar} from "./ClarityBar";import {DecisionResultView} from "./DecisionResultView";import {PrismMark} from "./PrismMark";
type Step="intro"|"goal"|"priority"|"experience"|"ownership";const steps:Step[]=["intro","goal","priority","experience","ownership"];
export function DecisionFlow(){const [idx,setIdx]=useState(0),[answers,setAnswers]=useState<DecisionAnswers>({}),[loading,setLoading]=useState(false),[done,setDone]=useState(false);const step=steps[idx];const can=useMemo(()=>step==="intro"||Boolean(answers[step]),[answers,step]);function choose(v:Goal|Priority|Experience|Ownership){setAnswers(a=>({...a,[step]:v}))}function next(){if(!can)return;if(idx<steps.length-1){setIdx(i=>i+1);return}setLoading(true);setTimeout(()=>{setLoading(false);setDone(true)},1800)}function restart(){setAnswers({});setIdx(0);setDone(false)}const Header=()=> <header><a className="brand" href="/"><PrismMark/><span><strong>PRISM</strong><small>Clarity before commitment.</small></span></a><div className="current"><span>Current decision</span><strong>Kitchen backsplash</strong></div></header>;
if(done)return <div><Header/><DecisionResultView result={evaluateBacksplash(answers as Required<DecisionAnswers>)} onRestart={restart}/></div>;
if(loading)return <div><Header/><main className="loading"><div className="orb"><span/></div><span className="eyebrow">Prism Decision Engine</span><h1>Building your strategy...</h1><p>✓ Understanding your outcome</p><p>✓ Weighing your priorities</p><p>✓ Evaluating DIY feasibility</p><p>Comparing viable strategies</p></main></div>;
return <div><Header/><main className="flow"><ClarityBar step={idx+1} total={steps.length}/>{step==="intro"?<section className="intro"><div><span className="eyebrow">Kitchen backsplash</span><h1>Find the smartest way to tackle your project.</h1><p>Prism compares DIY, hybrid, professional, and wait-and-plan strategies using your goals—not a generic checklist.</p><div className="pills"><span>About 2 minutes</span><span>4 questions</span><span>No contractor lead forms</span></div></div><aside><span className="label">What you will get</span><ul><li>A strategy matched to your situation</li><li>Why alternatives ranked lower</li><li>Your first three practical steps</li><li>Clear conditions for when to stop</li></ul></aside></section>:<Question step={step as Exclude<Step,"intro">} answers={answers} choose={choose}/>}<div className="actions"><button className="back" onClick={()=>setIdx(i=>Math.max(0,i-1))} disabled={idx===0}>Back</button><button className="primary" onClick={next} disabled={!can}>{idx===steps.length-1?"Build my strategy":"Continue"}</button></div></main></div>}
function Question({step,answers,choose}:{step:Exclude<Step,"intro">;answers:DecisionAnswers;choose:(v:Goal|Priority|Experience|Ownership)=>void}){const q=questions[step];return <section className="question"><span className="eyebrow">{q.eyebrow}</span><h1>{q.title}</h1><p>{q.helper}</p><div className="choices">{q.options.map(o=><ChoiceCard key={o.value} title={o.title} description={o.description} selected={answers[step]===o.value} onClick={()=>choose(o.value)}/>)}</div>{answers[step]&&<p className="ack">That helps. This answer will change how Prism compares the available strategies.</p>}</section>}
