import {strategyLabels} from "@/data/backsplash";
import type {DecisionAnswers,DecisionResult,StrategyId,StrategyScore} from "@/types/decision";
const ids:StrategyId[]=["diy","hybrid","professional","delay"];
function add(s:Record<StrategyId,number>,k:StrategyId,n:number){s[k]+=n}
export function evaluateBacksplash(a:Required<DecisionAnswers>):DecisionResult{
 const s:Record<StrategyId,number>={diy:50,hybrid:58,professional:54,delay:18};
 if(a.goal==="appearance"){add(s,"professional",12);add(s,"hybrid",10);add(s,"diy",4)}
 if(a.goal==="resale"){add(s,"professional",9);add(s,"hybrid",12);add(s,"diy",2);add(s,"delay",-8)}
 if(a.goal==="damage"){add(s,"professional",10);add(s,"hybrid",8);add(s,"delay",-18)}
 if(a.goal==="functionality"){add(s,"hybrid",8);add(s,"professional",7);add(s,"diy",5)}
 if(a.priority==="cost"){add(s,"diy",19);add(s,"hybrid",16);add(s,"professional",-12)}
 if(a.priority==="quality"){add(s,"professional",19);add(s,"hybrid",12);add(s,"diy",-7)}
 if(a.priority==="speed"){add(s,"professional",18);add(s,"hybrid",4);add(s,"diy",-10);add(s,"delay",-12)}
 if(a.priority==="risk"){add(s,"professional",16);add(s,"hybrid",11);add(s,"diy",-12)}
 if(a.priority==="longTerm"){add(s,"professional",12);add(s,"hybrid",13);add(s,"diy",2)}
 if(a.experience==="none"){add(s,"professional",15);add(s,"hybrid",14);add(s,"diy",-20)}
 if(a.experience==="some"){add(s,"hybrid",18);add(s,"diy",6);add(s,"professional",3)}
 if(a.experience==="experienced"){add(s,"diy",25);add(s,"hybrid",8);add(s,"professional",-6)}
 if(a.ownership==="sellingSoon"){add(s,"professional",9);add(s,"hybrid",11);add(s,"diy",-4)}
 if(a.ownership==="mediumTerm"){add(s,"hybrid",8);add(s,"professional",4);add(s,"diy",3)}
 if(a.ownership==="longTerm"){add(s,"professional",8);add(s,"hybrid",10);add(s,"diy",5)}
 const ranked:StrategyScore[]=ids.map(id=>({id,label:strategyLabels[id],score:Math.max(0,Math.min(100,s[id]))})).sort((x,y)=>y.score-x.score);
 return result(ranked[0],ranked.slice(1),a);
}
function result(w:StrategyScore,alts:StrategyScore[],a:Required<DecisionAnswers>):DecisionResult{
 if(w.id==="hybrid") return {winner:w,alternatives:alts,headline:"Use a hybrid approach.",summary:"Handle the lower-risk preparation yourself, then use a tile professional for the installation that determines the finished look.",reasons:[a.priority==="cost"?"You said controlling cost is the priority, and preparation is where your time can create meaningful savings.":"A hybrid path protects the finished result without paying a professional for every task.",a.experience==="some"?"Your DIY experience is useful for demolition, cleanup, outlet-cover removal, and wall preparation.":"You can own manageable work without learning tile installation on the most visible surface in the kitchen.",a.ownership==="longTerm"?"Because you expect to stay long-term, the professional finish is more valuable than minimizing the bill at all costs.":"This balances today’s budget with a clean result that should still support resale appeal."],whyNot:[{id:"diy",title:"Why full DIY ranked lower",explanation:"The installation carries the greatest visible rework risk. Small layout or cut errors can affect the entire wall."},{id:"professional",title:"Why full-service hiring ranked lower",explanation:"Paying for demolition, basic preparation, and cleanup adds cost without necessarily improving the installation."}],actionPlan:["Confirm the tile, pattern, grout color, and exact square footage.","Ask two installers to separate preparation and installation in their quotes.","DIY only the tasks both quotes agree can be completed safely before installation."],estimatedSavings:"$500–$1,200 versus full-service hiring",stopConditions:["Stop DIY preparation if removing tile tears away large sections of drywall.","Bring in a professional if you find moisture damage, mold, or electrical concerns.","Do not begin demolition until an installer confirms the surface they want to receive."]};
 if(w.id==="professional") return {winner:w,alternatives:alts,headline:"Hire a tile professional.",summary:"The finished result, timeline, and rework risk matter more in your situation than maximizing DIY savings.",reasons:["Your answers place a high value on finish quality, speed, or reducing mistakes.",a.experience==="none"?"This would be your first tile installation, and a backsplash puts alignment and cuts in constant view.":"Your current priorities favor consistency over learning during this project.",a.ownership==="sellingSoon"?"A professional result completed quickly is more likely to support broad resale appeal.":"The added cost supports a result you expect to live with for years."],whyNot:[{id:"hybrid",title:"Why hybrid ranked lower",explanation:"Splitting responsibility can create scheduling and surface-preparation disputes unless the installer approves the prep."},{id:"diy",title:"Why DIY ranked lower",explanation:"The learning curve introduces more finish and timeline risk than your priorities support."}],actionPlan:["Finalize the tile and pattern before requesting labor quotes.","Get two itemized quotes covering prep, outlets, grout, caulk, and cleanup.","Compare exclusions and installation method—not only total price."],stopConditions:["Do not hire from a verbal estimate without a written scope.","Pause if the quote does not address damaged drywall or wet-area preparation.","Do not choose the lowest bid until allowances and exclusions match."]};
 if(w.id==="diy") return {winner:w,alternatives:alts,headline:"DIY this project.",summary:"Your experience and priorities make a full DIY installation a realistic way to control cost and own the finished result.",reasons:["You have enough relevant experience to understand layout, cuts, adhesive, grout, and finish work.","The potential savings align strongly with what matters most to you.","Your ownership horizon gives you time to choose materials and complete the work carefully."],whyNot:[{id:"hybrid",title:"Why hybrid ranked lower",explanation:"Your experience reduces the value of paying a professional only for installation."},{id:"professional",title:"Why professional hiring ranked lower",explanation:"The higher cost is unlikely to produce enough additional value for your goals."}],actionPlan:["Create a full-scale layout plan before applying adhesive.","Complete a small practice board using the exact tile, cuts, grout, and caulk.","Set a stop point before demolition if the wall condition is worse than expected."],estimatedSavings:"$1,000–$2,500 versus professional installation",stopConditions:["Stop if the wall has moisture damage or requires extensive replacement.","Hire electrical help if outlets must be moved or wiring is damaged.","Switch to hybrid if the practice board does not meet your finish expectations."]};
 return {winner:w,alternatives:alts,headline:"Wait and plan this project.",summary:"There is not enough benefit or urgency in your answers to justify committing immediately.",reasons:["Your current priorities do not strongly favor spending or starting now.","Waiting creates time to define the design, budget, and desired outcome.","No answer indicates an urgent functional or safety concern."],whyNot:[{id:"diy",title:"Why DIY ranked lower",explanation:"Starting without a clear goal or finish standard increases rework risk."},{id:"professional",title:"Why hiring ranked lower",explanation:"A contractor cannot solve an unclear design decision without adding cost or compromise."}],actionPlan:["Save three backsplash designs you would be happy to live with.","Measure the area and establish an all-in spending limit.","Revisit the decision when the desired outcome is clear."],stopConditions:["Do not delay if damaged tile is exposing the wall to water.","Escalate if you discover loose material, mold, or electrical damage."]};
}
